name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Versions
        run: |
          git version
          cargo version

      - name: Install Musl cross-compiler
        # Unfortunately Ubuntu got the name of the compiler wrong so we have
        # to create a link for the correct name.
        run: >
          sudo apt-get -y install musl-tools &&
          sudo ln -s $(which musl-gcc) /usr/bin/x86_64-linux-musl-gcc &&
          rustup target add x86_64-unknown-linux-musl &&
          x86_64-linux-musl-gcc --version

      - name: Install QEMU
        run: sudo apt-get -y install qemu qemu-kvm

      - name: Install Transient
        run: pip3 install transient

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Run tests
        run: cd vm_test && cargo run
