name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Versions
        run: |
          git version
          cargo version

      - name: Install Musl target
        run: >
          sudo apt-get install musl-tools &&
          rustup target add x86_64-unknown-linux-musl &&
          musl-gcc --version

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: x86_64

      - name: Install Transient
        run: pip3 install transient

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Run tests
        run: cd vm_test && cargo run
