name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Note, musl-tools has a bug in ubuntu-20.04.
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2

      - name: Versions
        run: |
          git version
          cargo version

      - name: Install Musl cross-compiler
        # Unfortunately Ubuntu got the name of the compiler wrong so we have
        # to create a link for the correct name.
        run: >
          sudo apt-get -y install musl-tools &&
          sudo ln -s $(which musl-gcc) /usr/bin/x86_64-linux-musl-gcc &&
          rustup target add x86_64-unknown-linux-musl &&
          x86_64-linux-musl-gcc --version

      - name: Build
        run: cargo build --verbose --release --locked --target x86_64-unknown-linux-musl

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "target/x86_64-unknown-linux-musl/release/obliterate"
#           fail_on_unmatched_files: true  # I think this is not supported in the @v1 version.
